### ISSUE TITLE
Typo in paper, section 4.

### ISSUE THREAD

**Issue by sangminkim-99** [lzzcd001/GShell#1]
Hi @lzzcd001, Thank you for sharing this great work.
I just find a typo in your paper. 
Specifically, in Section 4, it seems that the mSDF value is presented as larger than 0, but it should be smaller than 0.

Thank you.

![image](https://github.com/lzzcd001/GShell/assets/65658464/6d6d3ade-2e1f-42ca-9fa9-4af3e10f86dc)

**Comment by sangminkim-99** [comment]
Additionally, if my understanding of the hole opening loss is accurate, the "tau" parameter within the loss function should be positioned within the Huber loss to ensure the mSDF value becomes smaller than 0. 
However, in equation 1, it appears that "tau" is located outside the scope of the loss function.

Thank you.

![image](https://github.com/lzzcd001/GShell/assets/65658464/5829e839-aa4d-44cf-a491-ee20696206e0)

**Comment by lzzcd001** [comment]
Hi Sangmin, thank you for pointing this typo out! We will upload an updated version soon.

The tau parameter serves merely as a loss coefficient (maybe this is clearer in the appendix), and the second term in this loss actually tries to push the mSDF values on the boundary to be positive. 

As a hypothetical example, let's suppose 1) the SDF values do not change at all (i.e., the watertight template is fixed) and 2) we drop the first term but only keep the second one. Since ``nu``'s  at iteration ``t`` are zero (as they are the mSDF values of the boundary points at iteration ``t``), ``(nu - epsilon)``'s are negative and ``nu``'s will be pushed to the positive side. As these ``nu``'s become positive at iteration ``t+1``, the holes contract.

**Comment by sangminkim-99** [comment]
Thank you for your explanation, @lzzcd001!
I'll check the supplementary for better understanding.

Thank you
